[package]
name = "crypto-bubbles-legacy-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.crypto-bubbles-legacy]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.39.2"
path = "../../../../../framework/meta"
