[package]
name = "factorial-meta"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@dharitri.com>"]
edition = "2021"
publish = false

[dependencies.factorial]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.39.7"
path = "../../../../framework/meta"
