[package]
name = "queue-repeat-meta"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@dharitri.com>"]
edition = "2021"
publish = false

[dependencies.queue-repeat]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.39.8"
path = "../../../../../framework/meta"
